# Generated by Django 4.2.4 on 2023-08-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image_user_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='닉네임', error_messages={'unique': '이미 존재하는 이름 또는 닉네임입니다.'}, max_length=8, unique=True, verbose_name='닉네임'),
            preserve_default=False,
        ),
    ]
