# Generated by Django 4.2.4 on 2023-08-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 존재하는 이름 또는 닉네임입니다.'}, help_text='닉네임은 최대 8글자 입니다.', max_length=8, unique=True, verbose_name='닉네임'),
        ),
    ]
