# Generated by Django 4.2.4 on 2023-08-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/default_profile_image.png', null=True, upload_to='users/profile', verbose_name='프로필 이미지'),
        ),
    ]
