# Generated by Django 4.2.4 on 2023-08-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnailImage',
            field=models.ImageField(blank=True, upload_to='community/board', verbose_name='썸네일'),
        ),
    ]
