# Generated by Django 4.2.4 on 2023-08-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_comment_modify_date_post_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewNum',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
