# Generated by Django 4.2.4 on 2023-08-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_post_viewnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notice_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='공지글'),
        ),
    ]
