# Generated by Django 4.2.4 on 2023-08-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_post_notice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnailImage',
        ),
    ]
