# Generated by Django 4.2.4 on 2023-08-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewNum', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('title', models.CharField(max_length=100, verbose_name='포스트 제목')),
                ('content', models.TextField(verbose_name='포스트 내용')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('thumbnailImage', models.ImageField(blank=True, upload_to='resources/share', verbose_name='썸네일')),
            ],
        ),
    ]
