# Generated by Django 4.2.4 on 2023-08-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharepost',
            name='subinfo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='부가 정보'),
        ),
    ]
