# Generated by Django 4.2.4 on 2023-08-28 08:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_sharepost_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepost',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='포스트 내용'),
        ),
    ]
