# Generated by Django 4.2.4 on 2023-08-28 08:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_sharepost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepost',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='포스트 내용'),
        ),
    ]
